services:
  db:
    image: postgres:16-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: watchdog
      POSTGRES_PASSWORD: watchdog
      POSTGRES_DB: watchdog
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
